### ISSUE TITLE
Counter component needs very long to be rendered

### ISSUE THREAD

**Issue by truthz03** [javiercn/CustomElementsBlazorSample#1]
Hi,

I tried this example because I need to render some Blazor components inside my Angular app.
I choose this example because I think it was an overkill to load the whole webassembly stuff and therefore I want to use serverside rendering.

The example is working but it took several minutes to show the counter component. In the meantime the page is completely empty.
After the component was rendered the first time and refreshing the browser tab it renders faster (about 1s)

What causes this reeeeaaaly long delay?

cc: @guardrex

**Comment by guardrex** [comment]
You should cross-link the article section, and I think they're going to ask you to put a GH repro app up so that they can see how you have your code structured.

**Comment by guardrex** [comment]
Oh ... and I didn't mean here on this repo. Sorry. Open the issue here ...

https://github.com/dotnet/aspnetcore/issues

... and close this issue.

**Comment by guardrex** [comment]
You can cross-link this sample in your issue there if this is what you're using. Then, you wouldn't need to put up a separate app on GH.
